
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
numpy = "^1.21.2"
matplotlib = "^3.5.0rc1"
PyQt5 = "^5.15.4"

[tool.pyflow.dev-dependencies]

