
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
pandas = "^1.3.3"
pyqt5 = "^5.15.4"
matplotlib = "^3.5.0rc1"
numpy = "^1.21.2"



[tool.pyflow.dev-dependencies]

